2009 - intégration périodique sauf carte
departement-loire-atlantique/jPlatformArchives pull request #29
Opened 2021-12-02 08:06 UTC by LChoquet

2021-12-02 09:36 UTC, sguellec requested changes
Balise fermante en trop (je crois) + posssibiltié d'utiliser la méthode "formatCategories" de SocleUtils pour simplifier le code.

2021-12-02 09:36 UTC, sguellec commented on plugins/ArchivesPlugin/types/Periodique/doPeriodiqueFullDisplay.jsp
> +                                            <%= itTheme.getName(userLang) %></a><%= itCounter < obj.getTheme(loggedMember).size() ? ", " : ""%>
Il me semble qu'il y a une balise fermante "a" et pas d'ouvrante. Pour info, si c'es tjsute de l'affichage sans lien il ya la méthode utilitaire "formatCategories" de SocleUtils qui génère une liste de catégories séparées par une virgule.

2021-12-02 09:36 UTC, sguellec commented on plugins/ArchivesPlugin/types/Periodique/doPeriodiqueFullDisplay.jsp
> +                                            <%= itPeriode.getName(userLang) %></a><%= itCounter < obj.getPeriode(loggedMember).size() ? ", " : ""%>
Même remarque que précédemment

2021-12-02 09:36 UTC, sguellec commented on plugins/ArchivesPlugin/types/Periodique/doPeriodiqueFullDisplay.jsp
> +                                            <%= itPolitique.getName(userLang) %></a><%= itCounter < obj.getTendencesPolitiques(loggedMember).size() ? ", " : ""%>
Idem

2021-12-02 09:36 UTC, sguellec commented on plugins/ArchivesPlugin/types/Periodique/doPeriodiqueFullDisplay.jsp
> +                           </jalios:foreach>
Idem, utiliser la méthode utilitaire, c'est juste que ça simplifie le code.

2021-12-02 09:51 UTC, LChoquet commented on plugins/ArchivesPlugin/types/Periodique/doPeriodiqueFullDisplay.jsp
> +                           </jalios:foreach>
Pas de méthode utilitaire pour les publications, seulement pour les catégories.
Si nécessaire cela peut être ajouté dans le module socle.

2021-12-02 14:23 UTC, sguellec commented on plugins/ArchivesPlugin/types/Periodique/doPeriodiqueFullDisplay.jsp
> +                           </jalios:foreach>
En effet, j'ai mal lu le code !

2021-12-02 14:23 UTC, sguellec approved these changes

2021-12-06 08:10 UTC, sguellec approved these changes

2021-12-06 08:11 UTC, merged